Fix: create channel for newly created rooms
When creating a new room via createRoom(), the response room was
added to the Redux store without a Phoenix Channel attached. This
caused a crash when the user tried to send a message:

  TypeError: undefined is not an object (evaluating 'room.channel.push')

Now mirrors the pattern used in componentDidMount: join the channel,
listen for incoming messages, then dispatch to the store.